### PR TITLE
Support for Azure and AWS on Gardener

### PR DESCRIPTION
**Pull request by Maladie**
**Description**

Changes proposed in this pull request:

- Support for provisioning AKS clusters via Gardener
- Support for provisioning AWS clusters via Gardener
- New examples added

**Related issue(s)**

https://github.com/kyma-incubator/compass/issues/403

### CODE REVIEW

**Comment by clebs** [comment]
Hi @Maladie,
first of all, thanks for your contribution.

The PR looks good and we would merge it, but unfortunately we are undergoing a gardener schema change at the moment to improve usability and add more configuration options (see https://github.com/kyma-incubator/hydroform/pull/27).

This will be merged next and therefore this PR will have to wait for a couple of days.
Sorry for the inconvenience.

**Comment by clebs** [comment]
Hi @Maladie,

we just merged the new gardener schema into Hydroform and it would be great if you could adapt your PR to the changes.

Thanks!

**Comment by Maladie** [comment]
Thanks @clebs, will do.

**Comment by Maladie** [comment]
@clebs PR adapted to new schema

**Pull request merged**
